### PR TITLE
2.1.0: Migration WebSQL to IndexedDB

### PR DESCRIPTION
**Pull request by afbora**
Will be merged and submitted to the directory after v2.0.0 approved in chrome extension directory.

### CODE REVIEW

**Comment by afbora** [comment]
Since WebSQL was removed in Chrome 119, I'm not sure if the WebSQL database is still stored. I haven't tested it exactly, but if Chrome hasn't deleted the WebSQL database yet, this migration will automatically transfer the data to indexeddb without doing anything 🤞

**Comment by afbora** [comment]
@fleps I'll need your helps to test the migration when this version available in chrome extension store 🙌

**Comment by fleps** [comment]
> @fleps I'll need your helps to test the migration when this version available in chrome extension store 🙌

For sure, let me know when! 👍

**Comment by afbora** [comment]
@fleps 2.1.0 is published, could you test it, please? 🤞 
https://chrome.google.com/webstore/detail/simple-time-tracker/ifdmgpcchapjlldljfegfdnojaieacmn

**Comment by fleps** [comment]
> @fleps 2.1.0 is published, could you test it, please? 🤞 https://chrome.google.com/webstore/detail/simple-time-tracker/ifdmgpcchapjlldljfegfdnojaieacmn

Hi @afbora 

Extension auto-updated this morning when I launched Chrome and all my previous tasks are restored.
Did a quick test of the features and all seems to be fine.

The updated UI also feels better.

Thanks for the quick fix and for this "Simple" extension =)

Cheers!

**Comment by afbora** [comment]
Great! 🎉 Thank you so much @fleps for the helps and contributing 💛

**Pull request merged**
